### ISSUE TITLE
Fix the title

### ISSUE THREAD

**Issue by luckyman20** [TEDxP/explore_WEB_TEMPLATES#3]
Currently the title is Scotch Digital we have to change it into **Coding worth Spreading**.

**Note** - **Spreading** should be in animation.

![capture](https://user-images.githubusercontent.com/20682192/34321129-13650ad2-e82e-11e7-9585-716a76768179.PNG)

**Comment by GBH** [comment]
You do realize that you cannot just rip https://digital.scotch.io/ designs, code and image assets, right?

**Comment by duttaditya18** [comment]
@0x48piraj Working on it!

**Comment by 0x48piraj** [comment]
@duttaditya18 Please see the UPDATE.

**Comment by duttaditya18** [comment]
@0x48piraj Is the animation required? Currently the problem that I am facing is that I cannot get the font to svg.

**Comment by 0x48piraj** [comment]
Okay, Plain fonts will do. Go ahead 👍

**Comment by 0x48piraj** [comment]
@duttaditya18 
I fixed the issue, we don't have much time :+1:
